INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (0, 'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (0, 'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (0, 'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (0, 'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (0, 'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (1, 'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (1, 'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (1, 'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (1, 'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (1, 'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (2, 'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (2, 'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (2, 'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (2, 'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (2, 'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (3, 'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (3, 'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (3, 'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (3, 'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (3, 'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (4, 'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (4, 'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (4, 'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (4, 'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (4, 'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (5, 'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (5, 'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (5, 'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (5, 'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId], [Day]) VALUES (5, 'Freitag')


INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (6,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (6,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (7,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (7,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (7,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (7,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (7,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (8,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (8,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (8,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (9,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (9,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (9,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (9,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (9,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (10,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (10,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (10,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (11,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (11,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (11,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (11,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (12,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (12,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (12,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (12,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (12,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (13,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (13,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (13,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (13,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (14,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (14,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (14,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (14,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (15,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (15,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (16,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (16,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (16,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (16,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (17,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (17,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (17,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (17,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (18,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (18,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (18,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (18,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (18,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (19,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (19,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (19,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (20,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (20,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (21,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (21,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (21,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (21,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (21,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (22,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (22,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (22,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (22,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (23,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (23,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (23,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (23,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (24,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (24,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (24,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (24,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (25,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (25,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (25,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (25,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (25,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (26,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (26,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (27,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (27,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (27,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (27,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (28,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (28,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (28,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (29,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (29,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (29,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (30,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (30,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (30,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (30,'Freitag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (31,'Montag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (31,'Dienstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (31,'Mittwoch')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (31,'Donnerstag')
INSERT INTO [dbo].[Plays_on] ([playerId],[Day]) VALUES (31,'Freitag')