INSERT INTO [dbo].[Weekday] ([Day]) VALUES ('Montag')
INSERT INTO [dbo].[Weekday] ([Day]) VALUES ('Dienstag')
INSERT INTO [dbo].[Weekday] ([Day]) VALUES ('Mittwoch')
INSERT INTO [dbo].[Weekday] ([Day]) VALUES ('Donnerstag')
INSERT INTO [dbo].[Weekday] ([Day]) VALUES ('Freitag')
INSERT INTO [dbo].[Weekday] ([Day]) VALUES ('Samstag')
INSERT INTO [dbo].[Weekday] ([Day]) VALUES ('Sonntag')
