INSERT INTO [dbo].[ScoreParameter] ([initialscore]) VALUES ('2000')
INSERT INTO [dbo].[ScoreParameter] ([scoredMatches]) VALUES ('100')
INSERT INTO [dbo].[ScoreParameter] ([halflife]) VALUES ('50')
INSERT INTO [dbo].[ScoreParameter] ([k-rating]) VALUES ('32')
INSERT INTO [dbo].[ScoreParameter] ([timepenalty]) VALUES ('50')
